name: AWS Code Build run
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  Code-Build-Run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::227531894161:role/GithubActionsRole
          aws-region: us-east-2
        
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: PullRequestCodeBuild
          buildspec-override: ../buildspec.yaml
