name: Quality Unit Test and Code Coverage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  Code-Build-Run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Requirements
        run: pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run tests and collect coverage
        run: pytest --cov=calculadora --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
      - codecov/upload
